### ISSUE TITLE
Creating a user after deleting throws exception

### ISSUE THREAD

**Issue by tonythomas01** [amfoss/club-website-2017#15] opened 2015-02-22 10:04 UTC
[Errno 2] No such file or directory: 'images/profile_image/joyceg.jpg'
Exception Type: OSError
Exception Value:  
[Errno 2] No such file or directory: 'images/profile_image/joyceg.jpg'
Exception Location: /home/domains/foss/fosswebsite/images/models.py in get_available_name, line 60

**Comment by ash1794** [comment] 2015-02-23 07:08
That's because the deletion of user doesn't delete the ProfileImage object which causes a conflict. Also deleting the ProfileImage object should delete the file. The necessary changes for the second part is already made when fixing Issue #8. I'm trying a fix. But the same error 503 might occur due to reasons mentioned in Issue #8.

**Comment by ash1794** [comment] 2015-03-02 13:35
Since The bug isn't reproduced. I'm closing this.

**Closed as completed by ash1794** 2015-03-02 13:35 UTC
Labels: high
