### ISSUE TITLE
Achievements link giving a 404 in amritafoss.in

### ISSUE THREAD

**Issue by dhanvi** [amfoss/club-website-2017#34] opened 2015-02-23 16:25 UTC
http://amritafoss.in/site/achievements

is giving me a 404 
![image](https://cloud.githubusercontent.com/assets/6671379/6331493/78a3e638-bba5-11e4-973a-b0a37c3ea07b.png)

but http://foss.amrita.ac.in/achievement/viewall/ works fine 

![screenshot from 2015-02-23 21 47 12](https://cloud.githubusercontent.com/assets/6671379/6331530/b378c076-bba5-11e4-96ae-67d1fc49f3f7.png)

Seems like amritafoss is not a exact clone of foss.amrita.ac.in and are running on two different servers and one of them is a windows one :-1: 

seems like we need to change the details for the website 

(also we need not have two different for two servers which are exactly the same, the problem can be removed by using cname )

also seems like we are publicizing the amritafoss in websites like https://kde.in/conf we should me it bug free :+1:

**Comment by ash1794** [comment] 2015-03-01 20:11
[Can't Reproduce Bug]
I don't see what's the Bug here. You've given two different URLs. Try giving the same URL to check if there is an issue next time.
Anyway there shouldn't be a problem using either Domain because it's just an change in the DNS entry.
Closing this issue.

**Closed as completed** 2015-03-02 11:38 UTC
